/*
   Brandon Danielski
   2/13/2017
   Assignment 2
   CS202
   This is the main function for the program.  It creates information to populate the popularity lists of each ride type and then runs the main menu of the app.
 */
#include"app.h"
#include"transport.h"
#include"rider.h"
int main()
{
	app the_app;
	the_app.first_greeting();
	transport* ptr_max = new MaxLine((char*)"MaxLine");
	transport* ptr_uber = new uber((char*)"uber");
	transport* ptr_Bus = new Bus((char*)"Bus");
	rider the_person;
	ptr_max->add_popularity_info(0,((char*)"1.25 "),15,((char*)"Early(12AM-5AM)"),((char*)"Monday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(0,((char*)"1.25 "),60,((char*)"Morning(5AM-11AM)"),((char*)"Monday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(0,((char*)"1.25 "),35,((char*)"Mid-day(11AM-5PM)"),((char*)"Monday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(0,((char*)"1.25 "),80,((char*)"Rush Hour(5PM-7PM)"),((char*)"Monday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(0,((char*)"1.25 "),40,((char*)"Evening(7PM-12AM)"),((char*)"Monday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(1,((char*)"1.25 "),10,((char*)"Early(12AM-5AM)"),((char*)"Tuesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(1,((char*)"1.25 "),56,((char*)"Morning(5AM-11AM)"),((char*)"Tuesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(1,((char*)"1.25 "),39,((char*)"Mid-day(11AM-5PM)"),((char*)"Tuesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(1,((char*)"1.25 "),76,((char*)"Rush Hour(5PM-7PM)"),((char*)"Tuesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(1,((char*)"1.25 "),33,((char*)"Evening(7PM-12AM)"),((char*)"Tuesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(2,((char*)"1.25 "),8,((char*)"Early(12AM-5AM)"),((char*)"Wednesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(2,((char*)"1.25 "),78,((char*)"Morning(5AM-11AM)"),((char*)"Wednesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(2,((char*)"1.25 "),43,((char*)"Mid-day(11AM-5PM)"),((char*)"Wednesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(2,((char*)"1.25 "),83,((char*)"Rush Hour(12AM-5AM)"),((char*)"Wednesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(2,((char*)"1.25 "),41,((char*)"Evening(7PM-12AM)"),((char*)"Wednesday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(3,((char*)"1.25 "),12,((char*)"Early(12AM-5AM)"),((char*)"Thursday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(3,((char*)"1.25 "),69,((char*)"Morning5AM-11AM)"),((char*)"Thursday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(3,((char*)"1.25 "),28,((char*)"Mid-day(11AM-5PM)"),((char*)"Thursday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(3,((char*)"1.25 "),76,((char*)"Rush Hour(5PM-7PM)"),((char*)"Thursday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(3,((char*)"1.25 "),50,((char*)"Evening(7PM-12AM)"),((char*)"Thursday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(4,((char*)"1.25 "),21,((char*)"Early(12AM-5AM)"),((char*)"Friday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(4,((char*)"1.25 "),91,((char*)"Morning(5AM-11AM)"),((char*)"Friday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(4,((char*)"1.25 "),54,((char*)"Mid-day(11AM-5PM)"),((char*)"Friday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(4,((char*)"1.25 "),96,((char*)"Rush Hour(5PM-7PM)"),((char*)"Friday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(4,((char*)"1.25 "),63,((char*)"Evening(7PM-12AM)"),((char*)"Friday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(5,((char*)"1.25 "),23,((char*)"Early(12AM-5AM)"),((char*)"Saturday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(5,((char*)"1.25 "),47,((char*)"Morning(5AM-11AM)"),((char*)"Saturday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(5,((char*)"1.25 "),53,((char*)"Mid-day(11AM-6PM)"),((char*)"Saturday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(5,((char*)"1.25 "),59,((char*)"Evening(6PM-12AM)"),((char*)"Saturday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(6,((char*)"1.25 "),31,((char*)"Early(12AM-5AM)"),((char*)"Sunday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(6,((char*)"1.25 "),40,((char*)"Morning(5AM-11AM)"),((char*)"Sunday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(6,((char*)"1.25 "),29,((char*)"mid-Day(11AM-6PM)"),((char*)"Sunday"),((char*)"MaxLine"));
	ptr_max->add_popularity_info(6,((char*)"1.25 "),14,((char*)"Evening(6PM-12AM)"),((char*)"Sunday"),((char*)"MaxLine"));

	ptr_uber->add_popularity_info(0,((char*)"5.15 "),10,((char*)"12AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.00 "),3,((char*)"1AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.00 "),4,((char*)"2AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.15 "),10,((char*)"3AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.28 "),17,((char*)"4AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.64 "),25,((char*)"5AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"6.06 "),40,((char*)"6AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"6.21 "),48,((char*)"7AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"6.06 "),40,((char*)"8AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.91 "),31,((char*)"9AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.63 "),24,((char*)"10AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.30 "),19,((char*)"11AM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.15 "),10,((char*)"12PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.19 "),12,((char*)"1PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.25 "),15,((char*)"2PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.15 "),10,((char*)"3PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.30 "),19,((char*)"4PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.68 "),28,((char*)"5PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.91 "),31,((char*)"6PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.66 "),27,((char*)"7PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.67 "),28,((char*)"8PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.69 "),29,((char*)"9PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.50 "),20,((char*)"10PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(0,((char*)"5.39 "),15,((char*)"11PM"),((char*)"Monday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.00 "),9,((char*)"12AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.00 "),6,((char*)"1AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.00 "),4,((char*)"2AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.00 "),7,((char*)"3AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.04 "),11,((char*)"4AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.17 "),19,((char*)"5AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.24 "),23,((char*)"6AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.41 "),32,((char*)"7AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.97 "),43,((char*)"8AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"6.00 "),43,((char*)"9AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.82 "),35,((char*)"10AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.76 "),33,((char*)"11AM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.65 "),28,((char*)"12PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.61 "),26,((char*)"1PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.56 "),23,((char*)"2PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.37 "),18,((char*)"3PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.67 "),27,((char*)"4PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.71 "),31,((char*)"5PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.98 "),39,((char*)"6PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.93 "),37,((char*)"7PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.95 "),38,((char*)"7PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"6.00 "),40,((char*)"8PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.87 "),34,((char*)"9PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.70 "),29,((char*)"10PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.30 "),19,((char*)"11PM"),((char*)"Tuesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.14 "),14,((char*)"12AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(1,((char*)"5.00 "),8,((char*)"1AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.00 "),7,((char*)"2AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.00 "),10,((char*)"3AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.28 "),16,((char*)"4AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.37 "),21,((char*)"5AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.43 "),26,((char*)"6AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.50 "),30,((char*)"7AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.68 "),34,((char*)"8AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.47 "),29,((char*)"9AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.37 "),27,((char*)"10AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.23 "),24,((char*)"11AM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.20 "),19,((char*)"12PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.17 "),17,((char*)"1PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.17 "),16,((char*)"2PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.14 "),15,((char*)"3PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.34 "),20,((char*)"4PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.35 "),26,((char*)"5PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.40 "),34,((char*)"6PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.39 "),33,((char*)"7PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.45 "),36,((char*)"8PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.40 "),32,((char*)"9PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.29 "),28,((char*)"10PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(2,((char*)"5.18 "),20,((char*)"11PM"),((char*)"Wednesday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.13 "),15,((char*)"12AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.10 "),13,((char*)"1AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.00 "),9,((char*)"2AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.00 "),6,((char*)"3AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.03 "),11,((char*)"4AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.16 "),18,((char*)"5AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.36 "),25,((char*)"6AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.42 "),33,((char*)"7AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.46 "),37,((char*)"8AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"6.00 "),40,((char*)"9AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.81 "),35,((char*)"10AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.60 "),28,((char*)"11AM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.54 "),22,((char*)"12PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.47 "),20,((char*)"1PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.40 "),18,((char*)"2PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.43 "),20,((char*)"3PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.55 "),28,((char*)"4PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.78 "),36,((char*)"5PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"6.23 "),44,((char*)"6PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"6.07 "),41,((char*)"7PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"6.12 "),42,((char*)"8PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.87 "),36,((char*)"9PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.59 "),28,((char*)"10PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(3,((char*)"5.35 "),20,((char*)"11PM"),((char*)"Thursday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.26 "),16,((char*)"12AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.14 "),13,((char*)"1AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.00 "),10,((char*)"2AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.00 "),9,((char*)"3AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.17 "),15,((char*)"4AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.30 "),20,((char*)"5AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.51 "),31,((char*)"6AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.96 "),39,((char*)"7AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"6.34 "),46,((char*)"8AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"6.87 "),51,((char*)"9AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"6.39 "),47,((char*)"10AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"6.00 "),40,((char*)"11AM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.32 "),35,((char*)"12PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.83 "),29,((char*)"1PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.10 "),26,((char*)"2PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.33 "),29,((char*)"3PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.29 "),34,((char*)"4PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.92 "),39,((char*)"5PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.40 "),43,((char*)"6PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.93 "),50,((char*)"7PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.01 "),56,((char*)"8PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.87 "),57,((char*)"9PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.24 "),53,((char*)"10PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(4,((char*)"5.64 "),48,((char*)"11PM"),((char*)"Friday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.83 "),42,((char*)"12AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.87 "),37,((char*)"1AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.43 "),28,((char*)"2AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.85 "),20,((char*)"3AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.20 "),18,((char*)"4AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.01 "),22,((char*)"5AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.43 "),25,((char*)"6AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.56 "),30,((char*)"7AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.35 "),31,((char*)"8AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.36 "),35,((char*)"9AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.70 "),36,((char*)"10AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.34 "),40,((char*)"11AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.02 "),37,((char*)"12AM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.33 "),35,((char*)"1PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.77 "),33,((char*)"2PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.43 "),30,((char*)"3PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.07 "),32,((char*)"4PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.43 "),39,((char*)"5PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.74 "),44,((char*)"6PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.93 "),48,((char*)"7PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.99 "),54,((char*)"8PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.34 "),60,((char*)"9PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.91 "),61,((char*)"10PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(5,((char*)"5.57 "),54,((char*)"11PM"),((char*)"Saturday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.92 "),48,((char*)"12AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.16 "),42,((char*)"1AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.08 "),38,((char*)"2AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.43 "),30,((char*)"3AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.65 "),25,((char*)"4AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.19 "),20,((char*)"5AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.84 "),16,((char*)"6AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.96 "),12,((char*)"7AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.04 "),15,((char*)"8AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.00 "),20,((char*)"9AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.24 "),23,((char*)"10AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.39 "),26,((char*)"11AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.22 "),29,((char*)"12AM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.07 "),30,((char*)"1PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.64 "),28,((char*)"2PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.32 "),25,((char*)"3PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.33 "),25,((char*)"4PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.92 "),26,((char*)"5PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.46 "),30,((char*)"6PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.22 "),33,((char*)"7PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.21 "),29,((char*)"8PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.89 "),23,((char*)"9PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.32 "),18,((char*)"10PM"),((char*)"Sunday"),((char*)"Uber"));
	ptr_uber->add_popularity_info(6,((char*)"5.33 "),14,((char*)"11PM"),((char*)"Sunday"),((char*)"Uber"));

	ptr_Bus->add_popularity_info(0,((char*)"2.00 "),44,((char*)"All Day"),((char*)"Monday"),((char*)"Bus"));
	ptr_Bus->add_popularity_info(1,((char*)"1.50 "),18,((char*)"All Day"),((char*)"Tuesday"),((char*)"Bus"));
	ptr_Bus->add_popularity_info(2,((char*)"1.00 "),22,((char*)"All Day"),((char*)"Wednesday"),((char*)"Bus"));
	ptr_Bus->add_popularity_info(3,((char*)"1.75 "),34,((char*)"All Day"),((char*)"Thursday"),((char*)"Bus"));
	ptr_Bus->add_popularity_info(4,((char*)"3.50 "),46,((char*)"All Day"),((char*)"Friday"),((char*)"Bus"));
	ptr_Bus->add_popularity_info(5,((char*)"4.00 "),74,((char*)"All Day"),((char*)"Saturday"),((char*)"Bus"));
	ptr_Bus->add_popularity_info(6,((char*)"3.00 "),52,((char*)"All Day"),((char*)"Sunday"),((char*)"Bus"));

	/*the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();
	  the_person.populate_history_data_at_random();*/

	char* price = (char*)"1.75";
	char* time = (char*)"3am";
	char* day = (char*)"Thursday";
	transport* hist1 = new Bus((char*)"Bus",price,8,time,day);
	price = (char*)"2.00";
	time = (char*)"3pm";
	day = (char*)"Monday";
	transport* hist2 = new Bus((char*)"Bus",price,8,time,day);
	price = (char*)"1.25";
	time = (char*)"8am";
	day = (char*)"Sunday";
	transport* hist3 = new MaxLine((char*)"MaxLine",price,8,time,day);
	price = (char*)"4.00";
	time = (char*)"12pm";
	day = (char*)"Saturday";
	transport* hist4 = new Bus((char*)"Bus",price,8,time,day);
	price = (char*)"1.25";
	time = (char*)"7am";
	day = (char*)"Monday";
	transport* hist5 = new MaxLine((char*)"MaxLine",price,8,time,day);
	price = (char*)"1.25";
	time = (char*)"11am";
	day = (char*)"Friday";
	transport* hist6 = new MaxLine((char*)"MaxLine",price,8,time,day);
	price = (char*)"4.00";
	time = (char*)"5pm";
	day = (char*)"Saturday";
	transport* hist7 = new Bus((char*)"Bus",price,8,time,day);
	price = (char*)"1.25";
	time = (char*)"10pm";
	day = (char*)"Wednesday";
	transport* hist8 = new MaxLine((char*)"MaxLine",price,8,time,day);
	price = (char*)"1.75";
	time = (char*)"12am";
	day = (char*)"Thursday";
	transport* hist9 = new Bus((char*)"Bus",price,8,time,day);
	price = (char*)"5.00";
	time = (char*)"3am";
	day = (char*)"Tuesday";
	transport* hist10 = new uber((char*)"uber",price,8,time,day);
	price = (char*)"3.00";
	time = (char*)"6am";
	day = (char*)"Sunday";
	transport* hist11 = new Bus((char*)"Bus",price,8,time,day);
	price = (char*)"1.75";
	time = (char*)"3am";
	day = (char*)"thursday";
	transport* hist12 = new Bus((char*)"Bus",price,8,time,day);

	the_person.add_ride_to_history(hist1);
	the_person.add_ride_to_history(hist2);
	the_person.add_ride_to_history(hist3);
	the_person.add_ride_to_history(hist4);
	the_person.add_ride_to_history(hist5);
	the_person.add_ride_to_history(hist6);
	the_person.add_ride_to_history(hist7);
	the_person.add_ride_to_history(hist8);
	the_person.add_ride_to_history(hist9);
	the_person.add_ride_to_history(hist10);
	the_person.add_ride_to_history(hist11);
	the_person.add_ride_to_history(hist12);
	the_app.main_menu(ptr_max,ptr_uber,ptr_Bus,the_person);
	delete ptr_max;
	delete ptr_uber;
	delete ptr_Bus;
	return 0;
}

